name: Rust

on:
  push:
    branches:
      - master
  pull_request: null

jobs:
  rust:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/alignof/seccampconnect2026:latest

    steps:
      - uses: actions/checkout@v4

      - name: Run clippy (push)
        uses: sksat/action-clippy@v1.1.1
        if: github.event_name == 'push'
        with:
          reporter: github-check

      - name: Run clippy (pull_request)
        uses: sksat/action-clippy@v1.1.1
        if: github.event_name == 'pull_request'
        with:
          reporter: github-pr-review

      - name: format check
        run: cargo fmt --all -- --check
